"""
cellregpy.plotting – MATLAB-matching diagnostic figures for CellRegPy.

All plot functions reproduce the figures generated by batchRunCellReg.m
so that Python results can be visually validated against the MATLAB output.
"""

from __future__ import annotations

import os
import numpy as np
import matplotlib.pyplot as plt
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Sequence, Tuple, Union

try:
    from scipy.ndimage import rotate as _nd_rotate
    from scipy.ndimage import shift as _nd_shift
    _HAVE_SCIPY = True
except Exception:
    _HAVE_SCIPY = False


# ============================================================================ #
#                     PLOTTING UTILITIES                                        #
# ============================================================================ #

def _as_list_of_2d(x, name):
    if x is None:
        raise ValueError(f"{name} is required")
    if isinstance(x, (list, tuple)):
        out = [np.asarray(a, dtype=float) for a in x]
    else:
        arr = np.asarray(x)
        if arr.ndim == 2:
            out = [arr.astype(float)]
        elif arr.ndim == 3:
            out = [arr[i].astype(float) for i in range(arr.shape[0])]
        else:
            raise ValueError(f"{name} must be 2D, 3D, or list/tuple of 2D arrays")
    for i, a in enumerate(out):
        if a.ndim != 2:
            raise ValueError(f"{name}[{i}] is not 2D (shape={a.shape})")
    return out


def _clamp01(x):
    x = np.asarray(x, dtype=float)
    x = np.nan_to_num(x, nan=0.0, posinf=0.0, neginf=0.0)
    x[x < 0] = 0
    x[x > 1] = 1
    return x


def _normalize01(x):
    x = np.asarray(x, dtype=float)
    x = np.nan_to_num(x, nan=0.0, posinf=0.0, neginf=0.0)
    mx = float(np.max(x)) if x.size else 0.0
    if mx <= 0:
        return np.zeros_like(x, dtype=float)
    return _clamp01(x / mx)


def make_rgb_overlay(A, B):
    """Red–green overlay of two images (red = A, green = B)."""
    A = np.asarray(A, dtype=float)
    B = np.asarray(B, dtype=float)
    A = np.nan_to_num(A, nan=0.0, posinf=0.0, neginf=0.0)
    B = np.nan_to_num(B, nan=0.0, posinf=0.0, neginf=0.0)
    mx = max(float(np.max(A)) if A.size else 0.0, float(np.max(B)) if B.size else 0.0, 1e-12)
    Ar = _clamp01(A / mx)
    Bg = _clamp01(B / mx)
    return np.stack([Ar, Bg, np.zeros_like(Ar)], axis=-1)


def corr2_nan(A, B):
    """2-D Pearson correlation ignoring NaNs."""
    A = np.asarray(A, dtype=float)
    B = np.asarray(B, dtype=float)
    mask = np.isfinite(A) & np.isfinite(B)
    if mask.sum() < 10:
        return float("nan")
    a = A[mask] - A[mask].mean()
    b = B[mask] - B[mask].mean()
    den = np.sqrt(np.sum(a * a) * np.sum(b * b))
    if den == 0:
        return float("nan")
    return float(np.sum(a * b) / den)


@dataclass
class BestTransform:
    tx: float; ty: float; rot_deg: float
    swap_xy: bool; signx: int; signy: int; signr: int; rot_then_trans: bool


def _apply_rigid_transform(img, tx, ty, rot_deg, *, rot_then_trans, fill=0.0):
    img = np.asarray(img, dtype=float)
    out = img
    if not _HAVE_SCIPY:
        raise ImportError("scipy is required for rigid transforms")
    def do_rot(x):
        return _nd_rotate(x, rot_deg, reshape=False, order=1, mode="constant", cval=fill) if rot_deg != 0 else x
    def do_shift(x):
        return _nd_shift(x, shift=(ty, tx), order=1, mode="constant", cval=fill) if (tx != 0 or ty != 0) else x
    if rot_then_trans:
        out = do_shift(do_rot(out))
    else:
        out = do_rot(do_shift(out))
    return out


def apply_transform_best(moving, ref, dx, dy, rot_deg=0.0):
    """Try all sign/swap combinations and pick the best rigid alignment."""
    best_score = -np.inf
    best_img = moving
    best_params = BestTransform(0, 0, 0, False, 1, 1, 1, True)
    for sw in [False, True]:
        for sx in [-1, 1]:
            for sy in [-1, 1]:
                for sr in [-1, 1]:
                    for rtt in [True, False]:
                        ttx = (sx * dy if sw else sx * dx)
                        tty = (sy * dx if sw else sy * dy)
                        r = sr * rot_deg
                        cand = _apply_rigid_transform(moving, tx=ttx, ty=tty, rot_deg=r, rot_then_trans=rtt, fill=0.0)
                        sc = corr2_nan(ref, cand)
                        if not np.isnan(sc) and sc > best_score:
                            best_score = sc
                            best_img = cand
                            best_params = BestTransform(float(ttx), float(tty), float(r), sw, sx, sy, sr, rtt)
    if best_score == -np.inf:
        best_score = float("nan")
    return best_img, best_params, float(best_score)


def _get_transform_params(alignment_translations, idx):
    if alignment_translations is None:
        return 0.0, 0.0, 0.0
    T = np.asarray(alignment_translations, dtype=float)
    dx = dy = rot = 0.0
    if T.ndim == 1:
        if T.size >= 2: dx, dy = float(T[0]), float(T[1])
        if T.size >= 3: rot = float(T[2])
        return dx, dy, rot
    if T.ndim != 2:
        return 0.0, 0.0, 0.0
    if T.shape[0] in (2, 3):
        if idx < T.shape[1]:
            dx, dy = float(T[0, idx]), float(T[1, idx])
            if T.shape[0] == 3: rot = float(T[2, idx])
    elif T.shape[1] in (2, 3):
        if idx < T.shape[0]:
            dx, dy = float(T[idx, 0]), float(T[idx, 1])
            if T.shape[1] == 3: rot = float(T[idx, 2])
    return dx, dy, rot


def get_session_score(scores, idx):
    if scores is None: return float("nan")
    try:
        if isinstance(scores, (list, tuple)):
            if idx >= len(scores): return float(scores[0]) if len(scores) else float("nan")
            v = scores[idx]
            if np.isscalar(v): return float(v)
            v = np.asarray(v).ravel(); v = v[np.isfinite(v)]
            return float(np.median(v)) if v.size else float("nan")
        arr = np.asarray(scores)
        if arr.ndim == 0: return float(arr)
        if idx < arr.size: return float(arr.ravel()[idx])
        return float(arr.ravel()[0])
    except Exception: return float("nan")


def session_names_to_labels(session_names, N):
    if not session_names:
        return [f"Session {i+1}" for i in range(N)]
    labels = []
    for nm in session_names:
        if nm is None: labels.append("(none)"); continue
        nm = str(nm)
        base = os.path.basename(nm.rstrip(os.sep))
        parent = os.path.basename(os.path.dirname(nm.rstrip(os.sep)))
        labels.append(parent if ("." in base and parent) else (base or nm))
    if len(labels) < N:
        labels.extend([f"Session {i+1}" for i in range(len(labels), N)])
    return labels[:N]


def savefig_both(fig, out_base, *, dpi=200, also_pdf=False, show=False):
    """Save figure to PNG (and optionally PDF) and display inline."""
    if out_base is not None:
        os.makedirs(os.path.dirname(out_base) or '.', exist_ok=True)
        fig.savefig(out_base + ".png", dpi=dpi, bbox_inches="tight")
        if also_pdf:
            fig.savefig(out_base + ".pdf", bbox_inches="tight")
    plt.show()


def _extract_p_from_model_string(model_string: str) -> float:
    """Extract the mixing weight p from the best_model_string."""
    try:
        return float(model_string.split(',')[0].split('=')[1])
    except Exception:
        return 0.5


def _compute_histogram_distribution(data, bin_centers, number_of_bins, scale=1.0):
    """Compute MATLAB-style normalized histogram distribution for model plotting."""
    d = np.asarray(data, dtype=np.float64)
    d = d[np.isfinite(d)]
    centers = np.asarray(bin_centers, dtype=np.float64)
    if len(centers) >= 2:
        step_c = centers[1] - centers[0]
        edges = np.empty(len(centers) + 1)
        edges[0] = centers[0] - step_c / 2
        for i in range(1, len(centers)):
            edges[i] = (centers[i - 1] + centers[i]) / 2
        edges[-1] = centers[-1] + step_c / 2
        counts, _ = np.histogram(d, bins=edges)
    else:
        counts = np.array([len(d)])
    counts = counts.astype(np.float64)
    step = scale * (centers[1] - centers[0]) if len(centers) > 1 else 1.0
    rng = scale * (centers[-1] - centers[0]) if len(centers) > 1 else 1.0
    denom = step + rng
    total = max(counts.sum(), 1.0)
    dist = counts / total * (number_of_bins / denom)
    return dist


# ============================================================================ #
#                     PLOTTING FUNCTIONS (MATLAB replicas)                      #
# ============================================================================ #

def plot_session_projections(footprints_projections, out_dir, show=False, also_pdf=False):
    """Plots grayscale projections of all sessions (Stage 1)."""
    if footprints_projections is None or len(footprints_projections) == 0:
        return
    num_sessions = len(footprints_projections)
    subx = 4
    suby = int(np.ceil(num_sessions / subx))
    if num_sessions <= 4:
        fig, axes = plt.subplots(1, num_sessions, figsize=(4 * num_sessions, 5))
        if num_sessions == 1: axes = [axes]
    else:
        fig, axes = plt.subplots(suby, subx, figsize=(4 * subx, 4 * suby))
    axes_flat = np.atleast_1d(axes).ravel()
    for i in range(len(axes_flat)):
        if i < num_sessions:
            proj = np.asarray(footprints_projections[i], dtype=float)
            axes_flat[i].imshow(proj, cmap='gray', vmin=0, vmax=2)
            axes_flat[i].set_xticks([]); axes_flat[i].set_yticks([])
            axes_flat[i].set_title(f'Session {i + 1}', fontsize=14, fontweight='bold')
        else:
            axes_flat[i].axis('off')
    savefig_both(fig, os.path.join(out_dir, "Stage 1 - spatial footprints projections") if out_dir else None,
                 also_pdf=also_pdf, show=show)


def validate_alignment_deck(
    mean_images, footprints_proj_raw, footprints_proj_aligned=None, *,
    reference_session_index=0, alignment_translations=None, scores=None,
    out_dir=".", session_names=None, show=False, also_pdf=False,
):
    """Generate the full alignment validation deck."""
    mean_images_l = _as_list_of_2d(mean_images, "mean_images")
    fp_raw_l = _as_list_of_2d(footprints_proj_raw, "footprints_proj_raw")
    fp_aligned_l = _as_list_of_2d(footprints_proj_aligned, "footprints_proj_aligned") if footprints_proj_aligned is not None else None
    N = len(mean_images_l)
    ref = int(reference_session_index)
    labels = session_names_to_labels(session_names, N)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    # Figure 1: overview
    order = [ref] + [i for i in range(N) if i != ref]
    fig1, axes = plt.subplots(nrows=N, ncols=3, figsize=(12, max(3, 2.2 * N)), constrained_layout=True)
    if N == 1: axes = np.array([axes])
    fig1.suptitle(f"Validation: reference vs all sessions | reference = {labels[ref]} (idx={ref+1})", fontweight="bold")
    for r, s in enumerate(order):
        ax = axes[r, 0]
        solo = fp_aligned_l[s] if fp_aligned_l is not None else fp_raw_l[s]
        ax.imshow(_normalize01(solo), cmap="gray"); ax.axis("off")
        ax.set_title(("REFERENCE\n" + labels[s] if s == ref else labels[s]), fontsize=9)
        ax = axes[r, 1]
        ax.imshow(make_rgb_overlay(fp_raw_l[ref], fp_raw_l[s])); ax.axis("off")
        ax.set_title("RAW overlay (R=ref, G=this)", fontsize=9)
        ax = axes[r, 2]
        if fp_aligned_l is not None:
            aligned = fp_aligned_l[s]
        else:
            dx, dy, rot = _get_transform_params(alignment_translations, s)
            aligned, _, _ = apply_transform_best(fp_raw_l[s], fp_raw_l[ref], dx, dy, rot)
        ref_img = fp_raw_l[ref] if fp_aligned_l is None else fp_aligned_l[ref]
        ax.imshow(make_rgb_overlay(ref_img, aligned)); ax.axis("off")
        sc = get_session_score(scores, s)
        sc_str = "n/a" if not np.isfinite(sc) else f"{sc:.3f}"
        ax.set_title(f"ALIGNED overlay (score={sc_str})", fontsize=9)
    savefig_both(fig1, os.path.join(out_dir, "Validation_ReferenceVsAllSessions_Footprints") if out_dir else None,
                 also_pdf=also_pdf)

    # Per-session panels
    for s in range(N):
        if s == ref: continue
        sc = get_session_score(scores, s)
        sc_str = "n/a" if not np.isfinite(sc) else f"{sc:.3f}"
        dx, dy, rot = _get_transform_params(alignment_translations, s)
        mean_s_aligned, best_tf, _ = apply_transform_best(mean_images_l[s], mean_images_l[ref], dx, dy, rot)
        fp_ref_raw = fp_raw_l[ref]; fp_s_raw = fp_raw_l[s]
        if fp_aligned_l is not None:
            fp_ref_aligned = fp_aligned_l[ref]; fp_s_aligned = fp_aligned_l[s]
        else:
            fp_s_aligned = _apply_rigid_transform(fp_s_raw, tx=best_tf.tx, ty=best_tf.ty, rot_deg=best_tf.rot_deg, rot_then_trans=best_tf.rot_then_trans, fill=0.0)
            fp_ref_aligned = fp_ref_raw
        fig2, ax = plt.subplots(nrows=2, ncols=2, figsize=(12, 10), constrained_layout=True)
        fig2.suptitle(f"Alignment Validation (Score: {sc_str}) | Ref={labels[ref]} vs {labels[s]}", fontweight="bold")
        ax[0,0].imshow(make_rgb_overlay(mean_images_l[ref], mean_images_l[s])); ax[0,0].set_title("Mean Images (Pre-Align)"); ax[0,0].axis("off")
        ax[0,1].imshow(make_rgb_overlay(mean_images_l[ref], mean_s_aligned)); ax[0,1].set_title("Mean Images ALIGNED"); ax[0,1].axis("off")
        ax[1,0].imshow(make_rgb_overlay(fp_ref_raw, fp_s_raw)); ax[1,0].set_title("Footprints RAW"); ax[1,0].axis("off")
        ax[1,1].imshow(make_rgb_overlay(fp_ref_aligned, fp_s_aligned)); ax[1,1].set_title("Footprints ALIGNED"); ax[1,1].axis("off")
        savefig_both(fig2, os.path.join(out_dir, f"Validation_Panel_Ref{ref+1}_vs_Sess{s+1}") if out_dir else None,
                     also_pdf=also_pdf, show=show)


def plot_x_y_displacements(
    neighbors_x_displacements, neighbors_y_displacements,
    microns_per_pixel, maximal_distance, number_of_bins, centers_of_bins,
    out_dir, show=False, also_pdf=False,
):
    """Plots (x,y) displacement distribution (Stage 3)."""
    if neighbors_x_displacements is None or neighbors_y_displacements is None:
        return
    x_disp = np.asarray(neighbors_x_displacements).ravel()
    y_disp = np.asarray(neighbors_y_displacements).ravel()
    mask = np.isfinite(x_disp) & np.isfinite(y_disp)
    x_disp, y_disp = x_disp[mask], y_disp[mask]
    if len(x_disp) == 0: return

    xout_temp_2 = np.linspace(0, maximal_distance, number_of_bins + 1)
    xout_2 = xout_temp_2[1::2]
    xy_centers = np.concatenate([-np.flip(xout_2), xout_2])
    n_xy = len(xy_centers)

    if n_xy > 1:
        step = xy_centers[1] - xy_centers[0]
        edges = np.concatenate([xy_centers - step / 2, [xy_centers[-1] + step / 2]])
    else:
        edges = np.array([-maximal_distance, maximal_distance])
    H, _, _ = np.histogram2d(x_disp, y_disp, bins=[edges, edges])
    H = np.flipud(np.fliplr(H))
    H_log = np.log1p(H)
    mx = float(np.max(H_log))
    if mx > 0: H_log /= mx

    fig = plt.figure(figsize=(8, 7))
    ax = fig.add_axes([0.12, 0.15, 0.75, 0.75])
    ax.imshow(H_log, aspect='equal', cmap='jet', interpolation='nearest', vmin=0, vmax=1)

    if isinstance(centers_of_bins, (list, tuple)):
        cob0 = np.asarray(centers_of_bins[0])
    else:
        cob0 = np.asarray(centers_of_bins).ravel()
    max_cob = float(np.max(cob0)) if len(cob0) else maximal_distance

    tick_positions = np.round(np.linspace(0, n_xy - 1, 9)).astype(int)
    y_labels = np.round(np.linspace(microns_per_pixel * max_cob, -microns_per_pixel * max_cob, 9)).astype(int)
    x_labels = np.round(np.linspace(-microns_per_pixel * max_cob, microns_per_pixel * max_cob, 9)).astype(int)
    ax.set_yticks(tick_positions); ax.set_yticklabels(y_labels, fontsize=14)
    ax.set_xticks(tick_positions); ax.set_xticklabels(x_labels, fontsize=14)
    ax.set_xlabel('x displacement (µm)', fontweight='bold', fontsize=14)
    ax.set_ylabel('y displacement (µm)', fontweight='bold', fontsize=14)

    theta = np.linspace(0, 2 * np.pi, 200)
    cx, cy = n_xy / 2, n_xy / 2
    r1 = n_xy / 2 * 4 / maximal_distance / microns_per_pixel
    r2 = n_xy / 2 * 8 / maximal_distance / microns_per_pixel
    ax.plot(cx + r1*np.sin(theta), cy + r1*np.cos(theta), ':', color='white', linewidth=4)
    ax.plot(cx + r2*np.sin(theta), cy + r2*np.cos(theta), '--', color='white', linewidth=4)

    cax = fig.add_axes([0.855, 0.15, 0.02, 0.75])
    cmap_jet = plt.cm.jet(np.linspace(0, 1, 64))
    for i in range(64):
        cax.fill_between([0, 1], i/64, (i+1)/64, color=cmap_jet[i])
    cax.set_xlim(0, 1); cax.set_ylim(0, 1); cax.set_xticks([]); cax.set_yticks([])
    cax.text(3.5, 0.5, 'Number of cell-pairs (log)', fontsize=14, fontweight='bold', rotation=90, ha='center', va='center', transform=cax.transAxes)

    savefig_both(fig, os.path.join(out_dir, "Stage 3 - (x,y) displacements") if out_dir else None,
                 also_pdf=also_pdf, show=show)


def plot_models(
    centroid_distances_model_parameters, NN_centroid_distances, NNN_centroid_distances,
    centroid_distances_distribution, centroid_distances_model_same_cells,
    centroid_distances_model_different_cells, centroid_distances_model_weighted_sum,
    centroid_distance_intersection, centers_of_bins_dist,
    spatial_correlations_model_parameters=None, NN_spatial_correlations=None,
    NNN_spatial_correlations=None, spatial_correlations_distribution=None,
    spatial_correlations_model_same_cells=None, spatial_correlations_model_different_cells=None,
    spatial_correlations_model_weighted_sum=None, spatial_correlation_intersection=None,
    centers_of_bins_corr=None, microns_per_pixel=1.0, maximal_distance=10.0,
    out_dir=".", show=False, also_pdf=False,
):
    """Plots probabilistic models (Stage 3)."""
    has_spatial = (spatial_correlations_model_parameters is not None)
    number_of_bins = len(centers_of_bins_dist)
    x_dist = microns_per_pixel * centers_of_bins_dist

    if number_of_bins > 1:
        step_d = centers_of_bins_dist[1] - centers_of_bins_dist[0]
        edges_dist = np.concatenate([centers_of_bins_dist - step_d/2, [centers_of_bins_dist[-1] + step_d/2]])
    else:
        edges_dist = np.linspace(0, maximal_distance, 10)
    n1_cd, _ = np.histogram(NN_centroid_distances, bins=edges_dist)
    n2_cd, _ = np.histogram(NNN_centroid_distances, bins=edges_dist)
    bar_offset_d = 0.25 * microns_per_pixel * maximal_distance / number_of_bins
    bar_width_d = 2 * bar_offset_d
    xtk_d = np.arange(0, microns_per_pixel * maximal_distance + 1, 3)

    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    fig.subplots_adjust(hspace=0.35, wspace=0.35)

    # subplot(2,2,1): Centroid histogram
    ax = axes[0, 0]
    ax.bar(x_dist + bar_offset_d, n1_cd, width=bar_width_d, color='g', edgecolor='none', label='Nearest neighbors')
    ax.bar(x_dist - bar_offset_d, n2_cd, width=bar_width_d, color='r', edgecolor='none', label='Other neighbors')
    ax.set_xlim(0, microns_per_pixel * maximal_distance)
    ax.set_xticks(xtk_d); ax.set_xticklabels(xtk_d.astype(int), fontsize=14)
    ax.set_xlabel('Centroids distance (µm)', fontweight='bold', fontsize=14)
    ax.set_ylabel('Number of cell-pairs', fontweight='bold', fontsize=14)

    # subplot(2,2,2): Spatial histogram
    if has_spatial:
        nn_sc = np.asarray(NN_spatial_correlations).ravel(); nn_sc = nn_sc[nn_sc >= 0]
        nnn_sc = np.asarray(NNN_spatial_correlations).ravel(); nnn_sc = nnn_sc[nnn_sc >= 0]
        x_corr = np.asarray(centers_of_bins_corr); n_bins_c = len(x_corr)
        if n_bins_c > 1:
            step_c = x_corr[1] - x_corr[0]
            edges_corr = np.concatenate([x_corr - step_c/2, [x_corr[-1] + step_c/2]])
        else:
            edges_corr = np.linspace(0, 1, 10)
        n1_sc, _ = np.histogram(nn_sc, bins=edges_corr)
        n2_sc, _ = np.histogram(nnn_sc, bins=edges_corr)
        bar_offset_c = 0.25 / n_bins_c; bar_width_c = 2 * bar_offset_c
        ax = axes[0, 1]
        ax.bar(x_corr + bar_offset_c, n1_sc, width=bar_width_c, color='g', edgecolor='none')
        ax.bar(x_corr - bar_offset_c, n2_sc, width=bar_width_c, color='r', edgecolor='none')
        ax.set_xlim(0, 1); ax.legend(loc='upper left', frameon=False)
        ax.set_xlabel('Spatial correlation', fontweight='bold', fontsize=14)
        ax.set_ylabel('Number of cell-pairs', fontweight='bold', fontsize=14)
    else:
        axes[0, 1].axis('off')

    # subplot(2,2,3): Centroid model
    ax_m = axes[1, 0]
    p_same = float(centroid_distances_model_parameters[0])
    bw_full = (x_dist[1] - x_dist[0]) if number_of_bins > 1 else 1.0
    ax_m.bar(x_dist, centroid_distances_distribution, width=bw_full, color='b', edgecolor='none', label='Observed data')
    ax_m.plot(x_dist, p_same * centroid_distances_model_same_cells, '--', color='g', linewidth=3, label='Same cell model')
    ax_m.plot(x_dist, (1 - p_same) * centroid_distances_model_different_cells, '--', color='r', linewidth=3, label='Different cells model')
    ax_m.plot(x_dist, centroid_distances_model_weighted_sum, '-', color='k', linewidth=3, label='Overall model')
    # Re-plot on top so dashed lines are visible over the solid black
    ax_m.plot(x_dist, p_same * centroid_distances_model_same_cells, '--', color='g', linewidth=3)
    ax_m.plot(x_dist, (1 - p_same) * centroid_distances_model_different_cells, '--', color='r', linewidth=3)
    if centroid_distance_intersection is not None and np.isfinite(centroid_distance_intersection):
        ci = float(centroid_distance_intersection)
        ymax_d = float(np.max(centroid_distances_distribution)) if len(centroid_distances_distribution) else 1
        ax_m.plot([ci, ci], [0, ymax_d], '--', color='k', linewidth=2)
        norm_same = centroid_distances_model_same_cells / max(centroid_distances_model_same_cells.sum(), 1e-12)
        norm_diff = centroid_distances_model_different_cells / max(centroid_distances_model_different_cells.sum(), 1e-12)
        same_above = float(norm_same[x_dist > ci].sum())
        diff_above = float(norm_diff[x_dist > ci].sum())
        ax_m.text(ci + 1, 0.9 * ymax_d, f'{round(100 * same_above)}%',
                  fontsize=14, fontweight='bold', ha='center', color='g')
        ax_m.text(ci - 1, 0.9 * ymax_d, f'{round(100 * (1 - same_above))}%',
                  fontsize=14, fontweight='bold', ha='center', color='g')
        ax_m.text(ci + 1, 0.8 * ymax_d, f'{round(100 * diff_above)}%',
                  fontsize=14, fontweight='bold', ha='center', color='r')
        ax_m.text(ci - 1, 0.8 * ymax_d, f'{round(100 * (1 - diff_above))}%',
                  fontsize=14, fontweight='bold', ha='center', color='r')
    ax_m.set_xlim(0, microns_per_pixel * maximal_distance)
    ax_m.set_xlabel('Centroids distance (µm)', fontweight='bold', fontsize=14)
    ax_m.set_ylabel('Probability density', fontweight='bold', fontsize=14)

    # subplot(2,2,4): Spatial model
    if has_spatial:
        ax_ms = axes[1, 1]
        p_same_s = float(spatial_correlations_model_parameters[0])
        bw_full_c = (x_corr[1] - x_corr[0]) if n_bins_c > 1 else 0.05
        ax_ms.bar(x_corr, spatial_correlations_distribution, width=bw_full_c, color='b', edgecolor='none', label='Observed data')
        ax_ms.plot(x_corr, p_same_s * spatial_correlations_model_same_cells, '--', color='g', linewidth=3, label='Same cell model')
        ax_ms.plot(x_corr, (1-p_same_s) * spatial_correlations_model_different_cells, '--', color='r', linewidth=3, label='Different cells model')
        ax_ms.plot(x_corr, spatial_correlations_model_weighted_sum, '-', color='k', linewidth=3, label='Overall model')
        ax_ms.plot(x_corr, p_same_s * spatial_correlations_model_same_cells, '--', color='g', linewidth=3)
        ax_ms.plot(x_corr, (1-p_same_s) * spatial_correlations_model_different_cells, '--', color='r', linewidth=3)
        if spatial_correlation_intersection is not None and np.isfinite(spatial_correlation_intersection):
            sci = float(spatial_correlation_intersection)
            ymax_s = float(np.max(spatial_correlations_distribution)) if len(spatial_correlations_distribution) else 1
            ax_ms.plot([sci, sci], [0, ymax_s], '--', color='k', linewidth=2)
            norm_same_s = spatial_correlations_model_same_cells / max(spatial_correlations_model_same_cells.sum(), 1e-12)
            norm_diff_s = spatial_correlations_model_different_cells / max(spatial_correlations_model_different_cells.sum(), 1e-12)
            same_above_s = float(norm_same_s[x_corr > sci].sum())
            diff_above_s = float(norm_diff_s[x_corr > sci].sum())
            ax_ms.text(sci + 0.1, 0.9 * ymax_s, f'{round(100 * same_above_s)}%',
                       fontsize=14, fontweight='bold', ha='center', color='g')
            ax_ms.text(sci - 0.1, 0.9 * ymax_s, f'{round(100 * (1 - same_above_s))}%',
                       fontsize=14, fontweight='bold', ha='center', color='g')
            ax_ms.text(sci + 0.1, 0.8 * ymax_s, f'{round(100 * diff_above_s)}%',
                       fontsize=14, fontweight='bold', ha='center', color='r')
            ax_ms.text(sci - 0.1, 0.8 * ymax_s, f'{round(100 * (1 - diff_above_s))}%',
                       fontsize=14, fontweight='bold', ha='center', color='r')
        ax_ms.set_xlim(0, 1)
        ax_ms.set_xlabel('Spatial correlation', fontweight='bold', fontsize=14)
        ax_ms.set_ylabel('Probability density', fontweight='bold', fontsize=14)
        ax_ms.legend(loc='upper left', frameon=False)
    else:
        axes[1, 1].axis('off')

    savefig_both(fig, os.path.join(out_dir, "Stage 3 - model") if out_dir else None,
                 also_pdf=also_pdf, show=show)


def plot_cell_scores(
    cell_scores, cell_scores_exclusive, cell_scores_positive, cell_scores_negative,
    p_same_registered_pairs, out_dir, show=False, also_pdf=False,
):
    """Plots score distributions (Stage 5)."""
    xout_temp = np.linspace(0, 1, 41)
    xout = xout_temp[1::2]
    step = xout[1] - xout[0] if len(xout) > 1 else 0.05
    edges = np.concatenate([xout - step/2, [xout[-1] + step/2]])
    number_of_clusters = len(cell_scores) if cell_scores is not None else 0
    size_x, size_y = 0.65, 0.65

    def _score_panel(fig, pos, inset_pos, data, xlabel_text, show_title=False):
        ax = fig.add_axes(pos)
        if data is None or len(data) == 0: return
        n1, _ = np.histogram(data, bins=edges)
        total = float(np.sum(n1))
        if total > 0: n1 = n1 / total
        ax.bar(xout, n1, width=step, color='steelblue')
        ax.set_xlim(0, 1); ax.set_ylim(0, 1)
        xtk = np.linspace(0, 1, 6)
        ax.set_xticks(xtk); ax.set_xticklabels([f'{v:.1f}' for v in xtk], fontsize=14, fontweight='bold')
        ax.set_xlabel(xlabel_text, fontsize=14, fontweight='bold')
        ax.set_ylabel('Probability', fontsize=14, fontweight='bold')
        if show_title:
            ax.text(-0.25, 1.2, f'{number_of_clusters} registered cells', fontsize=16, fontweight='bold', ha='center', transform=ax.transAxes)
        ax_in = fig.add_axes(inset_pos)
        ax_in.plot(np.flip(xout), np.cumsum(np.flip(n1)), linewidth=2)
        ax_in.set_ylim(0, 1); ax_in.invert_xaxis()
        xtk3 = np.linspace(0, 1, 3)
        ax_in.set_xticks(xtk3); ax_in.set_xticklabels([f'{v:.1f}' for v in xtk3], fontsize=14, fontweight='bold')
        ax_in.set_yticks(xtk3); ax_in.set_yticklabels([f'{v:.1f}' for v in xtk3], fontsize=14, fontweight='bold')
        ax_in.set_xlabel('Score', fontsize=14, fontweight='bold')
        ax_in.set_ylabel('Cum. fraction', fontsize=14, fontweight='bold')

    fig = plt.figure(figsize=(12, 10))
    sx2, sy2 = size_x/2, size_y/2
    _score_panel(fig, [0.12, 0.58, sx2, sy2], [0.2, 0.73, sx2/3, sy2/3], cell_scores_negative, 'True negative scores')
    _score_panel(fig, [0.6, 0.58, sx2, sy2], [0.68, 0.73, sx2/3, sy2/3], cell_scores_positive, 'True positive scores', show_title=True)
    _score_panel(fig, [0.12, 0.1, sx2, sy2], [0.2, 0.25, sx2/3, sy2/3], cell_scores_exclusive, 'Exclusivity cell scores')
    _score_panel(fig, [0.6, 0.1, sx2, sy2], [0.68, 0.25, sx2/3, sy2/3], cell_scores, 'Overall cell scores')
    savefig_both(fig, os.path.join(out_dir, "Stage 5 - cell scores") if out_dir else None,
                 also_pdf=also_pdf, show=show)

    # P_same pairs plot
    if p_same_registered_pairs is not None:
        p_pairs = []
        if isinstance(p_same_registered_pairs, (list, tuple)):
            for mat in p_same_registered_pairs:
                if mat is not None:
                    mat_arr = np.asarray(mat)
                    if mat_arr.ndim == 2:
                        rows_m, cols_m = mat_arr.shape
                        for k in range(rows_m):
                            for m in range(k+1, cols_m):
                                v = mat_arr[k, m]
                                if np.isfinite(v): p_pairs.append(v)
                    else:
                        v = mat_arr.ravel(); p_pairs.extend(v[np.isfinite(v)])
        elif isinstance(p_same_registered_pairs, np.ndarray):
            v = p_same_registered_pairs.ravel(); p_pairs = list(v[np.isfinite(v)])
        if len(p_pairs) > 0:
            p_pairs = np.array(p_pairs)
            fig2 = plt.figure(figsize=(6, 5))
            ax2 = fig2.add_axes([0.15, 0.15, 0.75, 0.75])
            n1_p, _ = np.histogram(p_pairs, bins=edges)
            total_p = float(np.sum(n1_p))
            if total_p > 0: n1_p = n1_p / total_p
            ax2.bar(xout, n1_p, width=step, color='steelblue')
            ax2.set_xlim(0, 1); ax2.set_ylim(0, 1)
            xtk = np.linspace(0, 1, 6)
            ax2.set_xticks(xtk); ax2.set_xticklabels([f'{v:.1f}' for v in xtk], fontsize=14, fontweight='bold')
            ax2.set_xlabel('Registered pairs P$_{same}$', fontsize=14, fontweight='bold')
            ax2.set_ylabel('Probability', fontsize=14, fontweight='bold')
            ax2_in = fig2.add_axes([0.3, 0.5, 0.3, 0.3])
            ax2_in.plot(np.flip(xout), np.cumsum(np.flip(n1_p)), linewidth=2)
            ax2_in.set_ylim(0, 1); ax2_in.invert_xaxis()
            xtk3 = np.linspace(0, 1, 3)
            ax2_in.set_xticks(xtk3); ax2_in.set_xticklabels([f'{v:.1f}' for v in xtk3], fontsize=14, fontweight='bold')
            ax2_in.set_yticks(xtk3); ax2_in.set_yticklabels([f'{v:.1f}' for v in xtk3], fontsize=14, fontweight='bold')
            ax2_in.set_xlabel('P$_{same}$', fontsize=14, fontweight='bold')
            ax2_in.set_ylabel('Cum. fraction', fontsize=14, fontweight='bold')
            savefig_both(fig2, os.path.join(out_dir, "Stage 5 - Registered pairs P_same") if out_dir else None,
                         also_pdf=also_pdf, show=show)


def plot_all_registered_projections(
    spatial_footprints, cell_to_index_map, out_dir, show=False, also_pdf=False, stage_label="Stage 5",
):
    """Plots projections of all cells. Green = cells in all sessions."""
    if spatial_footprints is None or cell_to_index_map is None:
        return
    if isinstance(spatial_footprints, np.ndarray) and spatial_footprints.dtype == object:
        fp_list = [np.asarray(e) for e in spatial_footprints.tolist()]
    elif isinstance(spatial_footprints, (list, tuple)):
        fp_list = [np.asarray(e) for e in spatial_footprints]
    else:
        return

    map_arr = np.asarray(cell_to_index_map)
    num_sessions = len(fp_list)
    if map_arr.shape[1] != num_sessions: return

    present_counts = np.sum(map_arr > 0, axis=1)
    idx_all = np.where(present_counts == num_sessions)[0]
    pixel_weight_threshold = 0.5

    projections = []
    for s in range(num_sessions):
        fps = fp_list[s]
        if fps.ndim != 3: continue
        c_idxs = map_arr[:, s].astype(int).copy()
        absent = c_idxs <= 0
        c_idxs -= 1
        c_idxs[absent] = -1

        h, w = fps.shape[1], fps.shape[2]
        normalized_fps = np.zeros_like(fps, dtype=float)
        for k in range(fps.shape[0]):
            fp = fps[k].astype(float)
            mx_fp = float(np.max(fp))
            if mx_fp > 0:
                fp[fp < pixel_weight_threshold * mx_fp] = 0
                normalized_fps[k] = fp / mx_fp

        idxs_all = c_idxs[idx_all]; idxs_all = idxs_all[idxs_all >= 0]
        other_mask = (c_idxs >= 0) & (present_counts < num_sessions)
        idxs_other = c_idxs[other_mask]; idxs_other = idxs_other[idxs_other >= 0]

        img_rgb = np.zeros((h, w, 3), dtype=float)
        sum_all = np.sum(normalized_fps[idxs_all], axis=0) if len(idxs_all) > 0 else np.zeros((h, w))
        sum_other = np.sum(normalized_fps[idxs_other], axis=0) if len(idxs_other) > 0 else np.zeros((h, w))
        img_rgb[..., 0] = sum_other
        img_rgb[..., 1] = sum_other + sum_all
        img_rgb[..., 2] = sum_other
        img_rgb = _clamp01(img_rgb)
        projections.append(img_rgb)

    if num_sessions <= 4:
        fig, axes = plt.subplots(1, num_sessions, figsize=(4 * num_sessions, 5))
        if num_sessions == 1: axes = [axes]
    else:
        subx = 4; suby = int(np.ceil(num_sessions / subx))
        fig, axes = plt.subplots(suby, subx, figsize=(4 * subx, 4 * suby))
    axes_flat = np.atleast_1d(axes).ravel()
    for i in range(len(axes_flat)):
        if i < num_sessions:
            axes_flat[i].imshow(projections[i])
            axes_flat[i].set_xticks([]); axes_flat[i].set_yticks([])
            axes_flat[i].set_title(f'Session {i + 1}', fontsize=14, fontweight='bold')
            if i == 0:
                h_img, w_img = projections[i].shape[0], projections[i].shape[1]
                axes_flat[i].text(0.01*w_img, 0.02*h_img, 'Detected in', fontsize=14, color='g', fontweight='bold')
                axes_flat[i].text(0.01*w_img, 0.06*h_img, 'all sessions', fontsize=14, color='g', fontweight='bold')
        else:
            axes_flat[i].axis('off')
    fname = f"{stage_label} - projections - {'initial' if '4' in stage_label else 'final'} registration"
    savefig_both(fig, os.path.join(out_dir, fname) if out_dir else None,
                 also_pdf=also_pdf, show=show)


def plot_init_registration(
    cell_to_index_map, number_of_bins, spatial_footprints, initial_registration_type,
    registered_cells, non_registered_cells, microns_per_pixel=1.0, maximal_distance=10.0,
    out_dir=".", show=False, also_pdf=False,
):
    """Plots initial registration results (Stage 4)."""
    fig = plt.figure(figsize=(8, 6))
    if initial_registration_type.lower().startswith('spatial'):
        xout = np.linspace(0, 1, number_of_bins)
        step = xout[1] - xout[0] if len(xout) > 1 else 0.05
        edges = np.concatenate([xout - step/2, [xout[-1] + step/2]])
        n1, _ = np.histogram(registered_cells, bins=edges)
        n2, _ = np.histogram(non_registered_cells, bins=edges)
        bar_offset = 0.25 / number_of_bins; bar_width = 2 * bar_offset
        ax = fig.add_axes([0.15, 0.15, 0.75, 0.75])
        ax.bar(xout + bar_offset, n1, width=bar_width, color='g', edgecolor='none', label='Same Cell')
        ax.bar(xout - bar_offset, n2, width=bar_width, color='r', edgecolor='none', label='Different Cells')
        ax.set_xlim(0, 1)
        ax.set_xlabel('Spatial correlation', fontweight='bold', fontsize=14)
    else:
        xout = np.linspace(0, maximal_distance, number_of_bins)
        step = xout[1] - xout[0] if len(xout) > 1 else 1.0
        edges = np.concatenate([xout - step/2, [xout[-1] + step/2]])
        n1, _ = np.histogram(registered_cells, bins=edges)
        n2, _ = np.histogram(non_registered_cells, bins=edges)
        bar_offset = 0.25 * microns_per_pixel * maximal_distance / number_of_bins; bar_width = 2 * bar_offset
        ax = fig.add_axes([0.15, 0.15, 0.75, 0.75])
        ax.bar(microns_per_pixel*xout + bar_offset, n1, width=bar_width, color='g', edgecolor='none', label='Same Cell')
        ax.bar(microns_per_pixel*xout - bar_offset, n2, width=bar_width, color='r', edgecolor='none', label='Different Cells')
        ax.set_xlim(0, microns_per_pixel * maximal_distance)
        ax.set_xlabel('Centroids distance (µm)', fontweight='bold', fontsize=14)
    ax.set_ylabel('Number of cell-pairs', fontweight='bold', fontsize=14)
    ax.tick_params(labelsize=14); ax.legend(loc='upper left', frameon=False)
    savefig_both(fig, os.path.join(out_dir, "Stage 4 - same versus different cells") if out_dir else None,
                 also_pdf=also_pdf, show=show)
    plot_all_registered_projections(spatial_footprints, cell_to_index_map, out_dir, show=show, also_pdf=also_pdf, stage_label="Stage 4")


def plot_pairwise_session_overlap(
    spatial_footprints, cell_to_index_map, out_dir, show=False,
):
    """Pairwise session overlap matrix.
    N×N grid: Red = session i only, Green = session j only, Yellow = shared.
    Diagonal = all cells for that session in white.
    """
    if spatial_footprints is None or cell_to_index_map is None:
        return

    if isinstance(spatial_footprints, np.ndarray) and spatial_footprints.dtype == object:
        fp_list = [np.asarray(e) for e in spatial_footprints.tolist()]
    elif isinstance(spatial_footprints, (list, tuple)):
        fp_list = [np.asarray(e) for e in spatial_footprints]
    else:
        return

    map_arr = np.asarray(cell_to_index_map)
    n_sessions = len(fp_list)
    if map_arr.shape[1] != n_sessions:
        print(f"Warning: map sessions ({map_arr.shape[1]}) != footprint sessions ({n_sessions})")
        return

    pixel_weight_threshold = 0.5

    norm_fps = []
    for s in range(n_sessions):
        fps = fp_list[s].astype(float)
        out = np.zeros_like(fps)
        for k in range(fps.shape[0]):
            mx = float(np.max(fps[k]))
            if mx > 0:
                fp = fps[k].copy()
                fp[fp < pixel_weight_threshold * mx] = 0
                out[k] = fp / mx
        norm_fps.append(out)

    def _to_0based(s):
        c = map_arr[:, s].astype(int).copy()
        absent = c <= 0
        c -= 1
        c[absent] = -1
        return c

    sess_idxs = [_to_0based(s) for s in range(n_sessions)]
    h, w = norm_fps[0].shape[1], norm_fps[0].shape[2]

    fig, axes = plt.subplots(n_sessions, n_sessions,
                             figsize=(4 * n_sessions, 4 * n_sessions))
    fig.suptitle('Pairwise Session Cell Overlap', fontsize=18, fontweight='bold', y=0.98)

    for i in range(n_sessions):
        for j in range(n_sessions):
            ax = axes[i][j] if n_sessions > 1 else axes

            if i == j:
                cells = sess_idxs[i][sess_idxs[i] >= 0]
                proj = np.zeros((h, w), dtype=float)
                if len(cells) > 0:
                    proj = np.clip(np.sum(norm_fps[i][cells], axis=0), 0, 1)
                ax.imshow(np.stack([proj, proj, proj], axis=-1))
                ax.set_title(f'Session {i+1}\n({len(cells)} cells)',
                             fontsize=12, fontweight='bold')
            else:
                both = (sess_idxs[i] >= 0) & (sess_idxs[j] >= 0)
                only_i = (sess_idxs[i] >= 0) & (sess_idxs[j] < 0)
                only_j = (sess_idxs[i] < 0) & (sess_idxs[j] >= 0)

                shared_proj = np.zeros((h, w), dtype=float)
                if both.sum() > 0:
                    si = sess_idxs[i][both]
                    sj = sess_idxs[j][both]
                    shared_proj = np.clip(
                        np.sum(norm_fps[i][si], axis=0) +
                        np.sum(norm_fps[j][sj], axis=0), 0, 1)

                proj_i = np.zeros((h, w), dtype=float)
                if only_i.sum() > 0:
                    proj_i = np.clip(np.sum(norm_fps[i][sess_idxs[i][only_i]], axis=0), 0, 1)
                proj_j = np.zeros((h, w), dtype=float)
                if only_j.sum() > 0:
                    proj_j = np.clip(np.sum(norm_fps[j][sess_idxs[j][only_j]], axis=0), 0, 1)

                r_ch = np.clip(proj_i + shared_proj, 0, 1)
                g_ch = np.clip(proj_j + shared_proj, 0, 1)
                ax.imshow(np.stack([r_ch, g_ch, np.zeros((h, w))], axis=-1))

                n_shared = int(both.sum())
                n_oi = int(only_i.sum())
                n_oj = int(only_j.sum())
                ax.set_title(f'S{i+1} vs S{j+1}\n{n_shared} shared',
                             fontsize=11, fontweight='bold')
                ax.text(3, h - 8, f'S{i+1} only: {n_oi}',
                        fontsize=9, color='red', fontweight='bold', va='bottom')
                ax.text(3, h - 22, f'S{j+1} only: {n_oj}',
                        fontsize=9, color='lime', fontweight='bold', va='bottom')

            ax.set_xticks([])
            ax.set_yticks([])
            if j == 0:
                ax.set_ylabel(f'Session {i+1}', fontsize=13, fontweight='bold')

    fig.tight_layout(rect=[0, 0, 1, 0.95])
    savefig_both(fig, os.path.join(out_dir, "Stage 5 - pairwise session overlap") if out_dir else None,
                 show=show)
